# version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/workspace
    command: sleep infinity

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  valkey:
    image: valkey/valkey:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - valkey-data:/data

volumes:
  mongo-data:
  valkey-data: